name: 'ada-actions/toolchain'
description: 'Setup an Ada development environment'
author: 'AdaCore'
branding:
  icon: 'box'
  color: 'green'
inputs:
  distrib:
    description: 'GNAT distribution (fsf or community)'
    default: 'fsf'
  target:
    description: 'Target architecture (native, arm-elf, riscv32-elf)'
    default: 'native'
  community_year:
    description: 'Year of the community release (2020, 2019)'
    default: '2020'
  install_dir:
    description: 'Path to a directory to install a community release'
    default: ''
runs:
  using: 'node12'
  main: 'lib/main.js'
